/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Specialist;

import javax.swing.JPanel;
import model.Business;
import model.ClinicManagement.TherapistProfile;
import model.InnovationManagement.SpecialistProfile;

/**
 *
 * @author Dell
 */
public class SpecialistWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel WorkArea;
    Business business;
    SpecialistProfile specialist;
    /**
     * Creates new form SpecialistWorkAreaJPanel
     */
    public SpecialistWorkAreaJPanel(Business b, SpecialistProfile sp, JPanel sjp) {
        business = b;
        this.WorkArea = sjp;
        specialist = sp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSpecialist = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        lblSpecialist.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSpecialist.setForeground(new java.awt.Color(255, 255, 255));
        lblSpecialist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpecialist.setText("SPECIALIST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSpecialist, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSpecialist, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSpecialist;
    // End of variables declaration//GEN-END:variables
}
