/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Nurse;


import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Business;
import model.ClinicManagement.NurseProfile;

/**
 *
 * @author Dell
 */
public class NurseWorkAreaJpanel extends javax.swing.JPanel {
    JPanel WorkArea;
    Business business;
    NurseProfile nurse;
    /**
     * Creates new form NurseWorkAreaJpanel
     */
    public NurseWorkAreaJpanel(Business b, NurseProfile np, JPanel njp) {
        business = b;
        this.WorkArea = njp;
        nurse = np;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNurse = new javax.swing.JLabel();
        btnMedication = new javax.swing.JButton();
        btnProgress = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnMedication1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        lblNurse.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNurse.setForeground(new java.awt.Color(255, 255, 255));
        lblNurse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNurse.setText("NURSE");

        btnMedication.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMedication.setForeground(new java.awt.Color(0, 102, 102));
        btnMedication.setText("Medication Details");
        btnMedication.setMaximumSize(new java.awt.Dimension(280, 50));
        btnMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicationActionPerformed(evt);
            }
        });

        btnProgress.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnProgress.setForeground(new java.awt.Color(0, 102, 102));
        btnProgress.setText("Progress Report ");
        btnProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgressActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("B A C K");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnMedication1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMedication1.setForeground(new java.awt.Color(0, 102, 102));
        btnMedication1.setText("Request Medication Details from Therapist");
        btnMedication1.setMaximumSize(new java.awt.Dimension(280, 50));
        btnMedication1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedication1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(btnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317)
                        .addComponent(btnProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnMedication1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(710, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnMedication1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicationActionPerformed
        // TODO add your handling code here:
        MedicationDetailsJPanel mdjp = new MedicationDetailsJPanel(business, WorkArea);
        WorkArea.add("MedicationDetails", mdjp);
        ((java.awt.CardLayout) WorkArea.getLayout()).next(WorkArea);
    }//GEN-LAST:event_btnMedicationActionPerformed

    private void btnProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgressActionPerformed
        // TODO add your handling code here:
        ProgressReportJPanel prjp = new ProgressReportJPanel(business, WorkArea);
        WorkArea.add("ProgressReport", prjp);
        ((java.awt.CardLayout) WorkArea.getLayout()).next(WorkArea);
    }//GEN-LAST:event_btnProgressActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        WorkArea.remove(this);
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.previous(WorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMedication1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedication1ActionPerformed
        // TODO add your handling code here:
        NurseWorkRequest prjp = new NurseWorkRequest(WorkArea, business);
        WorkArea.add("WR", prjp);
        ((java.awt.CardLayout) WorkArea.getLayout()).next(WorkArea);
    }//GEN-LAST:event_btnMedication1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMedication;
    private javax.swing.JButton btnMedication1;
    private javax.swing.JButton btnProgress;
    private javax.swing.JLabel lblNurse;
    // End of variables declaration//GEN-END:variables
}
