/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Processor;

<<<<<<< HEAD
import javax.swing.JPanel;
import model.Business;
import model.InnovationManagement.SpecialistProfile;
import model.InsuranceManagement.ProcessorProfile;

=======
>>>>>>> 2ba083150d082e3831f704026783b8c05b0a0984
/**
 *
 * @author Reva
 */
public class ProcessorWorkAreaJPanel extends javax.swing.JPanel {

<<<<<<< HEAD
    JPanel WorkArea;
    Business business;
    ProcessorProfile processor;
    /**
     * Creates new form ProcessorWorkAreaJPanel
     */
    public ProcessorWorkAreaJPanel(Business b, ProcessorProfile pp, JPanel pjp) {
        business = b;
        this.WorkArea = pjp;
        processor = pp;
        
=======
    /**
     * Creates new form ProcessorWorkAreaJPanel
     */
    public ProcessorWorkAreaJPanel() {
>>>>>>> 2ba083150d082e3831f704026783b8c05b0a0984
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNurse = new javax.swing.JLabel();
        btnProgress = new javax.swing.JButton();
        btnMedication = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        lblNurse.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblNurse.setForeground(new java.awt.Color(255, 255, 255));
        lblNurse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNurse.setText("PROCESSOR");

        btnProgress.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnProgress.setForeground(new java.awt.Color(0, 102, 102));
        btnProgress.setText("Documents");

        btnMedication.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMedication.setForeground(new java.awt.Color(0, 102, 102));
        btnMedication.setText("Claim Management");
        btnMedication.setMaximumSize(new java.awt.Dimension(280, 50));

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("B A C K");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(btnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317)
                        .addComponent(btnProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(914, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 655, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMedication;
    private javax.swing.JButton btnProgress;
    private javax.swing.JLabel lblNurse;
    // End of variables declaration//GEN-END:variables
}
