/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Educator;

<<<<<<< HEAD
import javax.swing.JPanel;
import model.Business;
import model.InnovationManagement.SpecialistProfile;
import model.PreHealthcareManagement.EducatorProfile;

=======
>>>>>>> 2ba083150d082e3831f704026783b8c05b0a0984
/**
 *
 * @author Reva
 */
public class EducatorWorkAreaJPanel extends javax.swing.JPanel {

<<<<<<< HEAD
    JPanel WorkArea;
    Business business;
    EducatorProfile educator;
    /**
     * Creates new form EducatorWorkAreaJPanel
     */
    public EducatorWorkAreaJPanel(Business b, EducatorProfile ep, JPanel ejp) {
        business = b;
        this.WorkArea = ejp;
        educator = ep;
=======
    /**
     * Creates new form EducatorWorkAreaJPanel
     */
    public EducatorWorkAreaJPanel() {
>>>>>>> 2ba083150d082e3831f704026783b8c05b0a0984
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
